<Project>
    <PropertyGroup>
        <Company>Moderne Inc.</Company>
        <PackageIcon>openrewrite.png</PackageIcon>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <VersionPrefix>0.3.3</VersionPrefix>
        <RewriteVersion>0.16.*</RewriteVersion>
    </PropertyGroup>
</Project>