<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Rewrite.Recipes</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Rewrite.CSharp" Version="$(RewriteVersion)" />
      <PackageReference Include="Rewrite.Properties" Version="$(RewriteVersion)" />
      <PackageReference Include="Rewrite.Json" Version="$(RewriteVersion)" />
      <PackageReference Include="Rewrite.Java" Version="$(RewriteVersion)" />
      <PackageReference Include="Rewrite.Core" Version="$(RewriteVersion)" />
    </ItemGroup>

</Project>
